targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/src/models/auth_cache_data.dart
          - lib/src/models/conversation_info.dart
          - lib/src/models/group_info.dart
          - lib/src/models/input_status_changed_data.dart
          - lib/src/models/message.dart
          - lib/src/models/notification_info.dart
          - lib/src/models/red_packet.dart
          - lib/src/models/search_info.dart
          - lib/src/models/set_group_member_info.dart
          - lib/src/models/update_req.dart
          - lib/src/models/user_full_info.dart
          - lib/src/models/user_info.dart