name: openim_sdk
description: An instant messaging plug-in that supports Android and IOS. And the server is also all open source.
version: 2.4.2
homepage: https://jsontodart.cn
repository: https://github.com/Matkurban/openim_sdk
topics: [ openim, im, sdk, flutter ]

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  meta: any
  dio: ^5.9.2
  path: ^1.9.1
  get_it: ^9.2.1
  crypto: ^3.0.7
  fixnum: ^1.1.1
  tostore: ^3.1.1
  protobuf: ^6.0.0
  equatable: ^2.0.8
  aoiwe_logger: ^1.0.1
  synchronized: ^3.4.0
  path_provider: ^2.1.5
  protoc_plugin: ^25.0.0
  json_annotation: ^4.11.0
  universal_platform: ^1.1.0
  web_socket_channel: ^3.0.3
  isolate_manager: ^6.3.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
  build_runner: ^2.13.1
  json_serializable: ^6.13.1
  isolate_manager_generator: ^0.4.1
